services:
  - type: web
    name: itunes-search-app
    env: node
    rootDir: .
    buildCommand: |
      npm install
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048" 
